// Generated by gencpp from file rockauto_msgs/AdjustXY.msg
// DO NOT EDIT!


#ifndef ROCKAUTO_MSGS_MESSAGE_ADJUSTXY_H
#define ROCKAUTO_MSGS_MESSAGE_ADJUSTXY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace rockauto_msgs
{
template <class ContainerAllocator>
struct AdjustXY_
{
  typedef AdjustXY_<ContainerAllocator> Type;

  AdjustXY_()
    : header()
    , x(0)
    , y(0)  {
    }
  AdjustXY_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , x(0)
    , y(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _x_type;
  _x_type x;

   typedef int32_t _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::rockauto_msgs::AdjustXY_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rockauto_msgs::AdjustXY_<ContainerAllocator> const> ConstPtr;

}; // struct AdjustXY_

typedef ::rockauto_msgs::AdjustXY_<std::allocator<void> > AdjustXY;

typedef boost::shared_ptr< ::rockauto_msgs::AdjustXY > AdjustXYPtr;
typedef boost::shared_ptr< ::rockauto_msgs::AdjustXY const> AdjustXYConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rockauto_msgs::AdjustXY_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rockauto_msgs::AdjustXY_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rockauto_msgs::AdjustXY_<ContainerAllocator1> & lhs, const ::rockauto_msgs::AdjustXY_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rockauto_msgs::AdjustXY_<ContainerAllocator1> & lhs, const ::rockauto_msgs::AdjustXY_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rockauto_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rockauto_msgs::AdjustXY_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rockauto_msgs::AdjustXY_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rockauto_msgs::AdjustXY_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rockauto_msgs::AdjustXY_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rockauto_msgs::AdjustXY_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rockauto_msgs::AdjustXY_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rockauto_msgs::AdjustXY_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0b992aab7c6f38b1fcd66efe02889fca";
  }

  static const char* value(const ::rockauto_msgs::AdjustXY_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0b992aab7c6f38b1ULL;
  static const uint64_t static_value2 = 0xfcd66efe02889fcaULL;
};

template<class ContainerAllocator>
struct DataType< ::rockauto_msgs::AdjustXY_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rockauto_msgs/AdjustXY";
  }

  static const char* value(const ::rockauto_msgs::AdjustXY_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rockauto_msgs::AdjustXY_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int32 x\n"
"int32 y\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::rockauto_msgs::AdjustXY_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rockauto_msgs::AdjustXY_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AdjustXY_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rockauto_msgs::AdjustXY_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rockauto_msgs::AdjustXY_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROCKAUTO_MSGS_MESSAGE_ADJUSTXY_H
