// Generated by gencpp from file rockauto_msgs/ImageObjRanged.msg
// DO NOT EDIT!


#ifndef ROCKAUTO_MSGS_MESSAGE_IMAGEOBJRANGED_H
#define ROCKAUTO_MSGS_MESSAGE_IMAGEOBJRANGED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <rockauto_msgs/ImageRectRanged.h>

namespace rockauto_msgs
{
template <class ContainerAllocator>
struct ImageObjRanged_
{
  typedef ImageObjRanged_<ContainerAllocator> Type;

  ImageObjRanged_()
    : header()
    , type()
    , obj()  {
    }
  ImageObjRanged_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , type(_alloc)
    , obj(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _type_type;
  _type_type type;

   typedef std::vector< ::rockauto_msgs::ImageRectRanged_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::rockauto_msgs::ImageRectRanged_<ContainerAllocator> >::other >  _obj_type;
  _obj_type obj;





  typedef boost::shared_ptr< ::rockauto_msgs::ImageObjRanged_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rockauto_msgs::ImageObjRanged_<ContainerAllocator> const> ConstPtr;

}; // struct ImageObjRanged_

typedef ::rockauto_msgs::ImageObjRanged_<std::allocator<void> > ImageObjRanged;

typedef boost::shared_ptr< ::rockauto_msgs::ImageObjRanged > ImageObjRangedPtr;
typedef boost::shared_ptr< ::rockauto_msgs::ImageObjRanged const> ImageObjRangedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rockauto_msgs::ImageObjRanged_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rockauto_msgs::ImageObjRanged_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rockauto_msgs::ImageObjRanged_<ContainerAllocator1> & lhs, const ::rockauto_msgs::ImageObjRanged_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.type == rhs.type &&
    lhs.obj == rhs.obj;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rockauto_msgs::ImageObjRanged_<ContainerAllocator1> & lhs, const ::rockauto_msgs::ImageObjRanged_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rockauto_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rockauto_msgs::ImageObjRanged_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rockauto_msgs::ImageObjRanged_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rockauto_msgs::ImageObjRanged_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rockauto_msgs::ImageObjRanged_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rockauto_msgs::ImageObjRanged_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rockauto_msgs::ImageObjRanged_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rockauto_msgs::ImageObjRanged_<ContainerAllocator> >
{
  static const char* value()
  {
    return "165d0348acd5a3d4df2930a42768b95f";
  }

  static const char* value(const ::rockauto_msgs::ImageObjRanged_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x165d0348acd5a3d4ULL;
  static const uint64_t static_value2 = 0xdf2930a42768b95fULL;
};

template<class ContainerAllocator>
struct DataType< ::rockauto_msgs::ImageObjRanged_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rockauto_msgs/ImageObjRanged";
  }

  static const char* value(const ::rockauto_msgs::ImageObjRanged_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rockauto_msgs::ImageObjRanged_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"string type\n"
"ImageRectRanged[] obj\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: rockauto_msgs/ImageRectRanged\n"
"ImageRect rect\n"
"float32 range\n"
"float32 min_height\n"
"float32 max_height\n"
"\n"
"================================================================================\n"
"MSG: rockauto_msgs/ImageRect\n"
"int32 x\n"
"int32 y\n"
"int32 height\n"
"int32 width\n"
"float32 score\n"
;
  }

  static const char* value(const ::rockauto_msgs::ImageObjRanged_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rockauto_msgs::ImageObjRanged_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.type);
      stream.next(m.obj);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImageObjRanged_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rockauto_msgs::ImageObjRanged_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rockauto_msgs::ImageObjRanged_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.type);
    s << indent << "obj[]" << std::endl;
    for (size_t i = 0; i < v.obj.size(); ++i)
    {
      s << indent << "  obj[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::rockauto_msgs::ImageRectRanged_<ContainerAllocator> >::stream(s, indent + "    ", v.obj[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROCKAUTO_MSGS_MESSAGE_IMAGEOBJRANGED_H
