// Generated by gencpp from file rockauto_msgs/NDTStat.msg
// DO NOT EDIT!


#ifndef ROCKAUTO_MSGS_MESSAGE_NDTSTAT_H
#define ROCKAUTO_MSGS_MESSAGE_NDTSTAT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace rockauto_msgs
{
template <class ContainerAllocator>
struct NDTStat_
{
  typedef NDTStat_<ContainerAllocator> Type;

  NDTStat_()
    : header()
    , exe_time(0.0)
    , iteration(0)
    , score(0.0)
    , velocity(0.0)
    , acceleration(0.0)
    , use_predict_pose(0)  {
    }
  NDTStat_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , exe_time(0.0)
    , iteration(0)
    , score(0.0)
    , velocity(0.0)
    , acceleration(0.0)
    , use_predict_pose(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _exe_time_type;
  _exe_time_type exe_time;

   typedef int32_t _iteration_type;
  _iteration_type iteration;

   typedef float _score_type;
  _score_type score;

   typedef float _velocity_type;
  _velocity_type velocity;

   typedef float _acceleration_type;
  _acceleration_type acceleration;

   typedef int32_t _use_predict_pose_type;
  _use_predict_pose_type use_predict_pose;





  typedef boost::shared_ptr< ::rockauto_msgs::NDTStat_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rockauto_msgs::NDTStat_<ContainerAllocator> const> ConstPtr;

}; // struct NDTStat_

typedef ::rockauto_msgs::NDTStat_<std::allocator<void> > NDTStat;

typedef boost::shared_ptr< ::rockauto_msgs::NDTStat > NDTStatPtr;
typedef boost::shared_ptr< ::rockauto_msgs::NDTStat const> NDTStatConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rockauto_msgs::NDTStat_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rockauto_msgs::NDTStat_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rockauto_msgs::NDTStat_<ContainerAllocator1> & lhs, const ::rockauto_msgs::NDTStat_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.exe_time == rhs.exe_time &&
    lhs.iteration == rhs.iteration &&
    lhs.score == rhs.score &&
    lhs.velocity == rhs.velocity &&
    lhs.acceleration == rhs.acceleration &&
    lhs.use_predict_pose == rhs.use_predict_pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rockauto_msgs::NDTStat_<ContainerAllocator1> & lhs, const ::rockauto_msgs::NDTStat_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rockauto_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rockauto_msgs::NDTStat_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rockauto_msgs::NDTStat_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rockauto_msgs::NDTStat_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rockauto_msgs::NDTStat_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rockauto_msgs::NDTStat_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rockauto_msgs::NDTStat_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rockauto_msgs::NDTStat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3c701a222db65bce735c83faea43bd03";
  }

  static const char* value(const ::rockauto_msgs::NDTStat_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3c701a222db65bceULL;
  static const uint64_t static_value2 = 0x735c83faea43bd03ULL;
};

template<class ContainerAllocator>
struct DataType< ::rockauto_msgs::NDTStat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rockauto_msgs/NDTStat";
  }

  static const char* value(const ::rockauto_msgs::NDTStat_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rockauto_msgs::NDTStat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float32 exe_time\n"
"int32 iteration\n"
"float32 score\n"
"float32 velocity\n"
"float32 acceleration\n"
"int32 use_predict_pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::rockauto_msgs::NDTStat_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rockauto_msgs::NDTStat_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.exe_time);
      stream.next(m.iteration);
      stream.next(m.score);
      stream.next(m.velocity);
      stream.next(m.acceleration);
      stream.next(m.use_predict_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NDTStat_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rockauto_msgs::NDTStat_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rockauto_msgs::NDTStat_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "exe_time: ";
    Printer<float>::stream(s, indent + "  ", v.exe_time);
    s << indent << "iteration: ";
    Printer<int32_t>::stream(s, indent + "  ", v.iteration);
    s << indent << "score: ";
    Printer<float>::stream(s, indent + "  ", v.score);
    s << indent << "velocity: ";
    Printer<float>::stream(s, indent + "  ", v.velocity);
    s << indent << "acceleration: ";
    Printer<float>::stream(s, indent + "  ", v.acceleration);
    s << indent << "use_predict_pose: ";
    Printer<int32_t>::stream(s, indent + "  ", v.use_predict_pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROCKAUTO_MSGS_MESSAGE_NDTSTAT_H
