// Generated by gencpp from file rockauto_msgs/ScanImage.msg
// DO NOT EDIT!


#ifndef ROCKAUTO_MSGS_MESSAGE_SCANIMAGE_H
#define ROCKAUTO_MSGS_MESSAGE_SCANIMAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace rockauto_msgs
{
template <class ContainerAllocator>
struct ScanImage_
{
  typedef ScanImage_<ContainerAllocator> Type;

  ScanImage_()
    : header()
    , distance()
    , intensity()
    , max_y(0)
    , min_y(0)  {
    }
  ScanImage_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , distance(_alloc)
    , intensity(_alloc)
    , max_y(0)
    , min_y(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _distance_type;
  _distance_type distance;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _intensity_type;
  _intensity_type intensity;

   typedef int32_t _max_y_type;
  _max_y_type max_y;

   typedef int32_t _min_y_type;
  _min_y_type min_y;





  typedef boost::shared_ptr< ::rockauto_msgs::ScanImage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rockauto_msgs::ScanImage_<ContainerAllocator> const> ConstPtr;

}; // struct ScanImage_

typedef ::rockauto_msgs::ScanImage_<std::allocator<void> > ScanImage;

typedef boost::shared_ptr< ::rockauto_msgs::ScanImage > ScanImagePtr;
typedef boost::shared_ptr< ::rockauto_msgs::ScanImage const> ScanImageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rockauto_msgs::ScanImage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rockauto_msgs::ScanImage_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rockauto_msgs::ScanImage_<ContainerAllocator1> & lhs, const ::rockauto_msgs::ScanImage_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.distance == rhs.distance &&
    lhs.intensity == rhs.intensity &&
    lhs.max_y == rhs.max_y &&
    lhs.min_y == rhs.min_y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rockauto_msgs::ScanImage_<ContainerAllocator1> & lhs, const ::rockauto_msgs::ScanImage_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rockauto_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rockauto_msgs::ScanImage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rockauto_msgs::ScanImage_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rockauto_msgs::ScanImage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rockauto_msgs::ScanImage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rockauto_msgs::ScanImage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rockauto_msgs::ScanImage_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rockauto_msgs::ScanImage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d3276ec225af95b58af799f4633b1f5d";
  }

  static const char* value(const ::rockauto_msgs::ScanImage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd3276ec225af95b5ULL;
  static const uint64_t static_value2 = 0x8af799f4633b1f5dULL;
};

template<class ContainerAllocator>
struct DataType< ::rockauto_msgs::ScanImage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rockauto_msgs/ScanImage";
  }

  static const char* value(const ::rockauto_msgs::ScanImage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rockauto_msgs::ScanImage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float32[] distance\n"
"float32[] intensity\n"
"int32 max_y\n"
"int32 min_y\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::rockauto_msgs::ScanImage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rockauto_msgs::ScanImage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.distance);
      stream.next(m.intensity);
      stream.next(m.max_y);
      stream.next(m.min_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ScanImage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rockauto_msgs::ScanImage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rockauto_msgs::ScanImage_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "distance[]" << std::endl;
    for (size_t i = 0; i < v.distance.size(); ++i)
    {
      s << indent << "  distance[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.distance[i]);
    }
    s << indent << "intensity[]" << std::endl;
    for (size_t i = 0; i < v.intensity.size(); ++i)
    {
      s << indent << "  intensity[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.intensity[i]);
    }
    s << indent << "max_y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.max_y);
    s << indent << "min_y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.min_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROCKAUTO_MSGS_MESSAGE_SCANIMAGE_H
