// Generated by gencpp from file rockauto_msgs/TrafficLightResultArray.msg
// DO NOT EDIT!


#ifndef ROCKAUTO_MSGS_MESSAGE_TRAFFICLIGHTRESULTARRAY_H
#define ROCKAUTO_MSGS_MESSAGE_TRAFFICLIGHTRESULTARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <rockauto_msgs/TrafficLightResult.h>

namespace rockauto_msgs
{
template <class ContainerAllocator>
struct TrafficLightResultArray_
{
  typedef TrafficLightResultArray_<ContainerAllocator> Type;

  TrafficLightResultArray_()
    : header()
    , results()  {
    }
  TrafficLightResultArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , results(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::rockauto_msgs::TrafficLightResult_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::rockauto_msgs::TrafficLightResult_<ContainerAllocator> >::other >  _results_type;
  _results_type results;





  typedef boost::shared_ptr< ::rockauto_msgs::TrafficLightResultArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rockauto_msgs::TrafficLightResultArray_<ContainerAllocator> const> ConstPtr;

}; // struct TrafficLightResultArray_

typedef ::rockauto_msgs::TrafficLightResultArray_<std::allocator<void> > TrafficLightResultArray;

typedef boost::shared_ptr< ::rockauto_msgs::TrafficLightResultArray > TrafficLightResultArrayPtr;
typedef boost::shared_ptr< ::rockauto_msgs::TrafficLightResultArray const> TrafficLightResultArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rockauto_msgs::TrafficLightResultArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rockauto_msgs::TrafficLightResultArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rockauto_msgs::TrafficLightResultArray_<ContainerAllocator1> & lhs, const ::rockauto_msgs::TrafficLightResultArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.results == rhs.results;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rockauto_msgs::TrafficLightResultArray_<ContainerAllocator1> & lhs, const ::rockauto_msgs::TrafficLightResultArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rockauto_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rockauto_msgs::TrafficLightResultArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rockauto_msgs::TrafficLightResultArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rockauto_msgs::TrafficLightResultArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rockauto_msgs::TrafficLightResultArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rockauto_msgs::TrafficLightResultArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rockauto_msgs::TrafficLightResultArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rockauto_msgs::TrafficLightResultArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2eb6bbdf62a95999f591812dc7ba8aa2";
  }

  static const char* value(const ::rockauto_msgs::TrafficLightResultArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2eb6bbdf62a95999ULL;
  static const uint64_t static_value2 = 0xf591812dc7ba8aa2ULL;
};

template<class ContainerAllocator>
struct DataType< ::rockauto_msgs::TrafficLightResultArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rockauto_msgs/TrafficLightResultArray";
  }

  static const char* value(const ::rockauto_msgs::TrafficLightResultArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rockauto_msgs::TrafficLightResultArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"TrafficLightResult[] results\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: rockauto_msgs/TrafficLightResult\n"
"# This message defines meta information for a traffic light status\n"
"Header header\n"
"\n"
"# Each bulb is assigned with an Id\n"
"# The TLR node convention is to use the yellow bulb's ID\n"
"int32 light_id\n"
"\n"
"# The result as provided by the tlr nodes\n"
"# Red and Yellow states are both treated as STOP\n"
"# RED       = 0\n"
"# YELLOW    = 0\n"
"# GREEN     = 1\n"
"# UNKNOWN   = 2\n"
"int32 recognition_result\n"
"\n"
"# This string is used by the Audio Player\n"
"string recognition_result_str\n"
"\n"
"# LaneId to which this traffic light result belongs to\n"
"# this Id is defined by the ADAS MAP\n"
"int32 lane_id\n"
"\n"
;
  }

  static const char* value(const ::rockauto_msgs::TrafficLightResultArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rockauto_msgs::TrafficLightResultArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.results);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrafficLightResultArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rockauto_msgs::TrafficLightResultArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rockauto_msgs::TrafficLightResultArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "results[]" << std::endl;
    for (size_t i = 0; i < v.results.size(); ++i)
    {
      s << indent << "  results[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::rockauto_msgs::TrafficLightResult_<ContainerAllocator> >::stream(s, indent + "    ", v.results[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROCKAUTO_MSGS_MESSAGE_TRAFFICLIGHTRESULTARRAY_H
