// Generated by gencpp from file rockauto_msgs/VscanTracked.msg
// DO NOT EDIT!


#ifndef ROCKAUTO_MSGS_MESSAGE_VSCANTRACKED_H
#define ROCKAUTO_MSGS_MESSAGE_VSCANTRACKED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>
#include <rockauto_msgs/GeometricRectangle.h>

namespace rockauto_msgs
{
template <class ContainerAllocator>
struct VscanTracked_
{
  typedef VscanTracked_<ContainerAllocator> Type;

  VscanTracked_()
    : position()
    , orientation(0.0)
    , velocity(0.0)
    , geo_rect()  {
    }
  VscanTracked_(const ContainerAllocator& _alloc)
    : position(_alloc)
    , orientation(0.0)
    , velocity(0.0)
    , geo_rect(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef float _orientation_type;
  _orientation_type orientation;

   typedef float _velocity_type;
  _velocity_type velocity;

   typedef  ::rockauto_msgs::GeometricRectangle_<ContainerAllocator>  _geo_rect_type;
  _geo_rect_type geo_rect;





  typedef boost::shared_ptr< ::rockauto_msgs::VscanTracked_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rockauto_msgs::VscanTracked_<ContainerAllocator> const> ConstPtr;

}; // struct VscanTracked_

typedef ::rockauto_msgs::VscanTracked_<std::allocator<void> > VscanTracked;

typedef boost::shared_ptr< ::rockauto_msgs::VscanTracked > VscanTrackedPtr;
typedef boost::shared_ptr< ::rockauto_msgs::VscanTracked const> VscanTrackedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rockauto_msgs::VscanTracked_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rockauto_msgs::VscanTracked_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rockauto_msgs::VscanTracked_<ContainerAllocator1> & lhs, const ::rockauto_msgs::VscanTracked_<ContainerAllocator2> & rhs)
{
  return lhs.position == rhs.position &&
    lhs.orientation == rhs.orientation &&
    lhs.velocity == rhs.velocity &&
    lhs.geo_rect == rhs.geo_rect;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rockauto_msgs::VscanTracked_<ContainerAllocator1> & lhs, const ::rockauto_msgs::VscanTracked_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rockauto_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rockauto_msgs::VscanTracked_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rockauto_msgs::VscanTracked_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rockauto_msgs::VscanTracked_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rockauto_msgs::VscanTracked_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rockauto_msgs::VscanTracked_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rockauto_msgs::VscanTracked_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rockauto_msgs::VscanTracked_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bff5c0a61020da26ef210837bea359b1";
  }

  static const char* value(const ::rockauto_msgs::VscanTracked_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbff5c0a61020da26ULL;
  static const uint64_t static_value2 = 0xef210837bea359b1ULL;
};

template<class ContainerAllocator>
struct DataType< ::rockauto_msgs::VscanTracked_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rockauto_msgs/VscanTracked";
  }

  static const char* value(const ::rockauto_msgs::VscanTracked_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rockauto_msgs::VscanTracked_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point position\n"
"float32 orientation\n"
"float32 velocity\n"
"GeometricRectangle geo_rect\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: rockauto_msgs/GeometricRectangle\n"
"float32 wl\n"
"float32 wr\n"
"float32 lf\n"
"float32 lb\n"
;
  }

  static const char* value(const ::rockauto_msgs::VscanTracked_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rockauto_msgs::VscanTracked_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.orientation);
      stream.next(m.velocity);
      stream.next(m.geo_rect);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VscanTracked_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rockauto_msgs::VscanTracked_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rockauto_msgs::VscanTracked_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "orientation: ";
    Printer<float>::stream(s, indent + "  ", v.orientation);
    s << indent << "velocity: ";
    Printer<float>::stream(s, indent + "  ", v.velocity);
    s << indent << "geo_rect: ";
    s << std::endl;
    Printer< ::rockauto_msgs::GeometricRectangle_<ContainerAllocator> >::stream(s, indent + "  ", v.geo_rect);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROCKAUTO_MSGS_MESSAGE_VSCANTRACKED_H
